import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Profile from "@/components/Profile";
import Login from "@/components/Login";
import ChangeColor from "@/components/ChangeColor";
import { useSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const themeColor = useSelector((state) => state.theme.value);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main style={{ background: themeColor }}>
				<Profile />
				<Login />
				<ChangeColor />
			</main>
		</>
	);
}
